### ISSUE TITLE
Destroy others functions.

### ISSUE THREAD

**Issue by sainf** [dynamick/multiple-filter-masonry#7]
The filter for me works well, but after clicking on one filter it destroy any function added to the masonry items.

Example: Simple JQuery Click, Magnific Popup...

My "non" solution has to fire the functions again to the masonry items in yours //reload masonry.

Any tip to make this script better?

**Comment by gocandra** [comment]
yes, same problem..

**Comment by jorgsuau** [comment]
Just put...
$( "body" ).change(function() {
  nameOfYourFunction(); //Put your functions here ...This detect any change in the body after to use the filter
});

And works fine again!
